In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [41]:
dataset = pd.read_csv(r'../data/creditcard.csv')
dataset.head(4)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0

In [42]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [43]:
dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [44]:
dataset['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [45]:
# 0 → Normal Transaction

# 1 → Fraudulent transaction

In [46]:
# separating the data for analysis

legit = dataset[dataset.Class == 0]
fraud = dataset[dataset.Class == 1]

In [47]:
# Statistical measures of data

legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [48]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [49]:
# compare the values of both 
dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [50]:
# select randomly 492 instances from legit transaction for equal distribution of both classes.
# it will balanced dataset suitable for training our fraud detection model.
# balancing the dataset enhances the models's accuracy

legit_sample = legit.sample(n=492)

In [51]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)
new_dataset.head(4)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
64731,51282.0,-1.350229,-1.019007,1.295775,0.754642,1.085331,-1.622792,-0.056931,0.042311,-0.084191,...,0.240830,0.018755,0.609225,0.310500,-0.511540,-0.751249,0.037780,0.150034,114.70,0
197972,132260.0,-2.106887,0.470926,-0.529202,-0.849676,1.125036,0.036699,0.858706,-0.790943,0.483707,...,0.355807,-0.639324,0.324237,0.086591,0.371871,-0.069899,0.309667,0.503001,99.07,0
225884,144437.0,-4.050630,3.985319,-2.871561,-1.779754,-0.210541,-1.981226,1.100614,0.289373,2.408374,...,-0.201740,0.611145,-0.037175,-0.040290,0.348068,0.066067,0.840774,0.332527,15.95,0
47724,43331.0,0.715555,-0.237858,0.868225,2.550445,-0.638177,0.039055,0.003682,0.102961,-0.753764,...,0.015251,-0.549091,-0.059513,0.279156,0.069263,-0.251861,-0.034631,0.059925,213.27,0

In [52]:
new_dataset.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [53]:
new_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94778.036585,0.045759,-0.015580,-0.011592,0.010724,-0.148892,0.013479,-0.038952,0.063227,-0.003274,...,0.025051,0.081753,0.018120,0.012206,-0.055114,-0.014890,0.010025,-0.013003,0.002966,102.641789
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [54]:
X = new_dataset.iloc[::-1]
Y = new_dataset["Class"]

In [55]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [56]:
print(X_train.shape, X_train.shape, X_test.shape)

(787, 31) (787, 31) (197, 31)

In [57]:
model = LogisticRegression()

In [58]:
# training the Logistic Regression modle with training data

model.fit(X_train, Y_train)

/home/satyajit-sahoo/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [59]:
model.score(X_train, Y_train) * 100

95.42566709021601

In [61]:
# accuracy on training data

training_data_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(training_data_prediction, Y_train)
training_data_accuracy * 100

95.42566709021601

In [62]:
# indicates that the model correctly predicts the class labels for arround 95.42% of the instaces in the training data.

In [63]:
# accuracy of training ata

test_data_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(test_data_prediction, Y_test)
test_data_accuracy * 100

93.4010152284264

In [64]:
# the accuracy score the test data is approximately 93.40%.
# this indicates the LR-model correctly predicts the class lables for around 93.40% of the instances in the testing data.