In [10]:
import pandas as pd

In [11]:
data = {"name":["a", "b", "c", "d", "a", "c"], "eng":[8, 7, 5, 8, 8, 4], "hindi":[2, 3, 4, 5, 2, 6]}

In [12]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    4      6

In [13]:
# df["is_duplicates"] = df.duplicated()

In [14]:
# df

In [16]:
# df.drop_duplicates(keep="first")
df.drop_duplicates(inplace=True)

In [17]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    4      6

In [18]:
dataset = pd.read_csv(r"/home/satyajit-sahoo/Downloads/bank-loan.csv")
dataset.head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area,married,Gender
0,41,3,17,12,NaN,9.3,11.359392,5.008608,1.0,Urban,No,Female
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural,Yes,Male
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban,Yes,Female
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,NaN,Yes,Male

In [21]:
dataset.shape

(850, 12)

In [22]:
dataset.drop_duplicates(inplace=True)

In [23]:
# dataset.duplicated()

In [24]:
dataset.shape

(850, 12)