In [58]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dataset = pd.read_csv(r"/home/satyajit-sahoo/Downloads/bank-loan.csv")
dataset.head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area
0,41,3,17,12,NaN,9.3,11.359392,5.008608,1.0,Urban
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,NaN

In [69]:
dataset.isnull().sum()

age           0
ed            0
employ        0
address       0
income        0
debtinc       0
creddebt      0
othdebt       0
default     150
area          0
dtype: int64

In [20]:
# dataset.fillna(20).head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area
0,41,3,17,12,20.0,9.3,11.359392,5.008608,1.0,Urban
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,20

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       850 non-null    int64
 1   ed        850 non-null    int64
 2   employ    850 non-null    int64
 3   address   850 non-null    int64
 4   income    849 non-null    float64
 5   debtinc   850 non-null    float64
 6   creddebt  850 non-null    float64
 7   othdebt   850 non-null    float64
 8   default   700 non-null    float64
 9   area      3 non-null      object
dtypes: float64(5), int64(4), object(1)
memory usage: 66.5+ KB

In [29]:
# dataset.fillna(method="bfill")

In [51]:
# axis=0 => column axis
# axis=1 => row axis

# dataset.fillna(method="ffill", axis=0).head(4)

In [63]:
dataset["income"] = dataset["income"].fillna(dataset["income"].mode()[0])

In [45]:
# dataset.info()

In [64]:
dataset.head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area
0,41,3,17,12,21.0,9.3,11.359392,5.008608,1.0,Urban
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,NaN

In [68]:
# filling mode in object type data
# dataset.select_dtypes(include="object").isnull().sum()
for i in dataset.select_dtypes(include="object").columns:
    dataset[i] = dataset[i].fillna(dataset[i].mode()[0])

In [60]:
# dataset.head(4)