In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dataset = pd.read_csv(r"/home/satyajit-sahoo/Downloads/bank-loan.csv")
dataset.head(4)

   age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     NaN      9.3  11.359392  5.008608      1.0
1   27   1      10        6    31.0     17.3   1.362202  4.000798      0.0
2   40   1      15       14    55.0      5.5   0.856075  2.168925      0.0
3   41   1      15       14   120.0      2.9   2.658720  0.821280      0.0

In [2]:
dataset.isnull().sum()

age           0
ed            0
employ        0
address       0
income        1
debtinc       0
creddebt      0
othdebt       0
default     150
dtype: int64

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       850 non-null    int64
 1   ed        850 non-null    int64
 2   employ    850 non-null    int64
 3   address   850 non-null    int64
 4   income    849 non-null    float64
 5   debtinc   850 non-null    float64
 6   creddebt  850 non-null    float64
 7   othdebt   850 non-null    float64
 8   default   700 non-null    float64
dtypes: float64(5), int64(4)
memory usage: 59.9 KB

In [6]:
dataset.select_dtypes(include="float64").columns

Index(['income', 'debtinc', 'creddebt', 'othdebt', 'default'], dtype='object')

In [30]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy="mean")

ar = si.fit_transform(dataset[['income', 'debtinc', 'creddebt', 'othdebt', 'default']])

# pd.DataFrame(si.fit_transform(dataset[['income', 'debtinc', 'creddebt', 'othdebt', 'default']]), columns=dataset.select_dtypes(include="float64").columns)

In [25]:
new_dataset = pd.DataFrame(ar,columns=dataset.select_dtypes(include="float64").columns)
# new_dataset.isnull().sum()

income      0
debtinc     0
creddebt    0
othdebt     0
default     0
dtype: int64

In [26]:
new_dataset.isnull().sum()

income      0
debtinc     0
creddebt    0
othdebt     0
default     0
dtype: int64

In [27]:
new_dataset

         income  debtinc   creddebt   othdebt   default
0     46.522968      9.3  11.359392  5.008608  1.000000
1     31.000000     17.3   1.362202  4.000798  0.000000
2     55.000000      5.5   0.856075  2.168925  0.000000
3    120.000000      2.9   2.658720  0.821280  0.000000
4     28.000000     17.3   1.787436  3.056564  1.000000
..          ...      ...        ...       ...       ...
845   32.000000      2.7   0.239328  0.624672  0.261429
846  116.000000      5.7   4.026708  2.585292  0.261429
847   38.000000     10.8   0.722304  3.381696  0.261429
848   24.000000      7.8   0.417456  1.454544  0.261429
849   41.000000     12.9   0.899130  4.389870  0.261429

[850 rows x 5 columns]

In [29]:
dataset["default"].mean()

0.26142857142857145