In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("./data/placement.csv")
dataset.head(3)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25

In [3]:
x = dataset.iloc[:,:-1]
y = dataset["package"]

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [8]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_train, y_train)*100, lr.score(x_test, y_test)*100

(77.58339025733345, 77.30984312051673)

In [9]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
dt.score(x_train, y_train)*100, dt.score(x_test, y_test)*100

(95.1559200955432, 52.19733481708333)

In [10]:
svr = SVR()
svr.fit(x_train, y_train)
svr.score(x_train, y_train)*100, svr.score(x_test, y_test)*100

(78.16909319813372, 75.94945442913415)

 # Ensemble Learning

In [11]:
from sklearn.ensemble import VotingRegressor

In [14]:
li = [("lr1", LinearRegression()), ("dt1", DecisionTreeRegressor()), ("svr1", SVR())]

In [15]:
vr = VotingRegressor(li)

In [16]:
vr.fit(x_train, y_train)

VotingRegressor(estimators=[('lr1', LinearRegression()),
                            ('dt1', DecisionTreeRegressor()), ('svr1', SVR())])

In [18]:
vr.score(x_train, y_train)*100, vr.score(x_test, y_test)*100

(87.56852979319457, 75.16568331690885)

In [20]:
df = {"lr":lr.predict(x_test), "dt": dt.predict(x_test), "svr":svr.predict(x_test), "vr": vr.predict(x_test)}

In [22]:
pd.DataFrame(df)

          lr        dt       svr        vr
0   2.780313  2.920000  2.745462  2.815259
1   3.136352  3.252500  3.111375  3.166742
2   3.199521  2.920000  3.186923  3.102148
3   2.389819  2.540000  2.407183  2.445667
4   3.526847  3.990000  3.603909  3.706919
5   3.768035  4.110000  3.864755  3.914263
6   3.165065  3.330000  3.145318  3.213461
7   2.544868  2.235000  2.544422  2.441430
8   3.176550  3.330000  3.159083  3.221878
9   3.492392  3.140000  3.560946  3.397779
10  1.907444  1.995000  1.861447  1.921297
11  2.349621  2.570000  2.367828  2.429150
12  3.687639  3.890000  3.787063  3.788234
13  2.757343  1.940000  2.724923  2.474089
14  3.475164  3.250000  3.539138  3.421434
15  3.044471  2.850000  3.007404  2.967292
16  2.326651  2.436667  2.344391  2.369236
17  3.205263  2.920000  3.193945  3.106403
18  2.177344  2.550000  2.174781  2.300708
19  3.314372  3.310000  3.331379  3.318584
20  2.452987  2.580000  2.465325  2.499437
21  2.900907  3.185000  2.858757  2.981555
22  3.320115  3.310000  3.338777  3.322964
23  2.872195  3.110000  2.830893  2.937696
24  3.337342  2.770000  3.361030  3.156124
25  2.194572  2.100000  2.195711  2.163428
26  1.419326  1.940000  2.069395  1.809573
27  2.711403  3.020000  2.684696  2.805366
28  3.182293  3.420000  3.166005  3.256099
29  2.326651  2.436667  2.344391  2.369236
30  3.745064  3.420000  3.843594  3.669553
31  2.958333  2.970000  2.916291  2.948208
32  3.681896  3.760000  3.781130  3.741009
33  2.975561  3.080000  2.934040  2.996534
34  2.590809  3.180000  2.582838  2.784549
35  3.348827  2.770000  3.375907  3.164912
36  2.475958  2.200000  2.485568  2.387175
37  3.073184  3.030000  3.039129  3.047438
38  4.175757  3.330000  4.107480  3.871079
39  2.958333  2.970000  2.916291  2.948208